### PR TITLE
run tests also with Babel

### PR DESCRIPTION
**Pull request by sisp**
This PR adds support for running the test suite with Babel in addition to `tsc` (via `ts-jest`), especially regarding decorator compatibility with Babel's transpilation.

### CODE REVIEW

**Comment by sisp** [comment]
One test is failing, but I don't understand why ... :thinking:

**Comment by xaviergonz** [comment]
Because of this babel decorators plugin bug: https://github.com/babel/babel/issues/11131
I'll push a fix in a sec

**Comment by xaviergonz** [comment]
Thanks!!

**Comment by sisp** [comment]
Ah, again that bug ... Thanks for the fix! 🙂

**Pull request merged**
