### PR TITLE
add findParentWithPath

### PR DESCRIPTION
**Pull request by xaviergonz**

### CODE REVIEW

**Comment by sisp** [comment]
Any particular reason why you named this function `findParentWithPath` and not `findParentPath`? I thought the latter would be more consistent with `getParent`/`getParentPath` (=> `findParent`/`findParentPath`).

**Comment by xaviergonz** [comment]
findParentPath made me think of finding the parent and then its path (like my first comment to your suggestion)

**Comment by sisp** [comment]
I see. For the sake of consistency, would you say it makes sense to rename `getParentPath` to `getParentWithPath` then?

**Comment by xaviergonz** [comment]
Ok, you convinced me, findParentPath it is :)

**Pull request merged**
