### PR TITLE
try to fix inheritance for es6

### LINKED ISSUE #15: create-react-app: TypeError: Class constructor [...] cannot be invoked without 'new'
When using `ExtendedModel` in a `create-react-app`-based app, I'm getting the following error:

> TypeError: Class constructor [...] cannot be invoked without 'new'

This is a minimal reproduction: https://github.com/sisp/mobx-keystone-cra-issue

The error does not occur when I run the example with `ts-node`, so I think the problem originates from CRA's usage of Babel + Typescript build chain.

### PR DESCRIPTION
**Pull request by xaviergonz**
Fixes #15

### CODE REVIEW

**Comment by xaviergonz** [comment]
@sisp care to give this build a try and see if it fixes your CRA issue?

**Comment by sisp** [comment]
When I use the ESM bundle built from this branch with my [CRA example](https://github.com/sisp/mobx-keystone-cra-issue), it works (for both `"target": "es5"` and `"target": "es6"` in `tsconfig.json`). :-)

**Comment by sisp** [comment]
Do you think it makes sense to add a comment in the code that justifies this "hack" and references #15 for referring to the discussion about the problem?

**Comment by xaviergonz** [comment]
Makes total sense, added, will release this as 0.13.1

**Comment by sisp** [comment]
Thanks a lot for your efforts! You're awesome!

**Pull request merged**
