### PR TITLE
Deprecate prop modifier variant withSetter("assign")

### PR DESCRIPTION
**Pull request by sisp**
Clarifies usage of `prop().withSetter("assign")` in the docs. Resolves #268.

### CODE REVIEW

**Comment by xaviergonz** [comment]
the assign mode is legacy and deprecated, that's why it is not documented

**Comment by sisp** [comment]
Ah, I didn't know. Should we update the docs stating it's legacy or just leave things as they are?

**Comment by xaviergonz** [comment]
I guess the former so people don't get confused 😅

**Comment by sisp** [comment]
I've updated the PR to deprecate `withSetter("assign")` using the JSDoc tag `@deprecated` and documented the deprecation in the docs. What do you think?

**Comment by xaviergonz** [comment]
Thanks!

**Pull request merged**
