### PR TITLE
Benchmark extensions to test creation from snapshots and against es6 & raw mobx

### PR DESCRIPTION
**Pull request by airhorns**
This adds a couple more bits to the benchmarking setup to help compare MST and this awesome library:

 - Add a benchmark for creating instances from snapshots that already have data in them
 - Add raw es6 classes comparison and raw mobx comparison to the benchmark

Plain old JS classes are not really a substitute for mobx-y anything, but, it's useful to know how much overhead the libraries introduce over the simplest way you might do the same thing in plain old JS. Similarly, it's nice to know what overhead is mobx's fault vs these libraries fault. I kept the benchmark reporting smart enough to only compare mobx-keystone and mobx-state-tree, and then log how much faster the es6 implementation is and the mobx implementation is just for reference.

Here's what I get when running with typechecking on and typechecking off locally:

```
empty creation (type checking enabled) - mst is usually faster here due to lazy creation
mobx-keystone x 4,169 ops/sec ±6.12% (75 runs sampled)
mobx-state-tree x 4,545 ops/sec ±6.51% (85 runs sampled)
raw es6 x 191,813 ops/sec ±2.73% (90 runs sampled)
raw mobx x 17,260 ops/sec ±1.07% (90 runs sampled)
Fastest is mobx-state-tree by 1.09x
raw mobx is faster by 3.80x
raw es6 is faster by 42.20x

empty creation + access all simple props (type checking enabled)
mobx-keystone x 4,668 ops/sec ±3.54% (81 runs sampled)
mobx-state-tree x 2,334 ops/sec ±3.36% (82 runs sampled)
raw es6 x 196,179 ops/sec ±0.45% (93 runs sampled)
raw mobx x 17,918 ops/sec ±0.58% (94 runs sampled)
Fastest is mobx-keystone by 2.00x
raw mobx is faster by 3.84x
raw es6 is faster by 42.02x

already created, access all simple props (type checking enabled)
mobx-keystone x 341,406 ops/sec ±0.56% (95 runs sampled)
mobx-state-tree x 297,739 ops/sec ±2.64% (90 runs sampled)
raw es6 x 3,294,078 ops/sec ±2.71% (91 runs sampled)
raw mobx x 989,796 ops/sec ±1.02% (93 runs sampled)
Fastest is mobx-keystone by 1.15x
raw mobx is faster by 2.90x
raw es6 is faster by 9.65x

snapshot creation (type checking enabled)
mobx-keystone x 4,384 ops/sec ±2.92% (82 runs sampled)
mobx-state-tree x 5,130 ops/sec ±2.07% (90 runs sampled)
raw es6 x 190,180 ops/sec ±0.48% (95 runs sampled)
raw mobx x 17,085 ops/sec ±1.43% (91 runs sampled)
Fastest is mobx-state-tree by 1.17x
raw mobx is faster by 3.33x
raw es6 is faster by 37.07x

already created, access all simple props (type checking enabled)
mobx-keystone x 331,105 ops/sec ±1.15% (92 runs sampled)
mobx-state-tree x 312,005 ops/sec ±1.80% (91 runs sampled)
raw es6 x 3,448,649 ops/sec ±0.59% (93 runs sampled)
raw mobx x 986,882 ops/sec ±1.24% (89 runs sampled)
Fastest is mobx-keystone by 1.06x
raw mobx is faster by 2.98x
raw es6 is faster by 10.42x

already created, change all simple props (type checking enabled)
mobx-keystone x 1,903 ops/sec ±1.84% (87 runs sampled)
mobx-state-tree x 1,447 ops/sec ±3.06% (83 runs sampled)
raw es6 x 1,717 ops/sec ±1.40% (89 runs sampled)
raw mobx x 1,605 ops/sec ±2.18% (87 runs sampled)
Fastest is mobx-keystone by 1.32x
raw mobx is faster by 0.84x
raw es6 is faster by 0.90x

already created, change one simple props + getSnapshot (type checking enabled)
mobx-keystone x 62,599 ops/sec ±1.76% (90 runs sampled)
mobx-state-tree x 34,634 ops/sec ±1.91% (90 runs sampled)
raw es6 x 7,136,654 ops/sec ±62.88% (30 runs sampled)
raw mobx:
Fastest is mobx-keystone by 1.81x
raw mobx is faster by 0.00x
raw es6 is faster by 114.01x

empty creation (type checking disabled) - mst is usually faster here due to lazy creation
mobx-keystone x 4,305 ops/sec ±6.24% (79 runs sampled)
mobx-state-tree x 4,165 ops/sec ±8.03% (80 runs sampled)
raw es6 x 186,264 ops/sec ±7.02% (86 runs sampled)
raw mobx x 16,673 ops/sec ±2.56% (85 runs sampled)
Fastest is mobx-keystone by 1.03x
raw mobx is faster by 3.87x
raw es6 is faster by 43.27x

empty creation + access all simple props (type checking disabled)
mobx-keystone x 4,146 ops/sec ±18.43% (76 runs sampled)
mobx-state-tree x 2,339 ops/sec ±3.22% (83 runs sampled)
raw es6 x 183,910 ops/sec ±1.26% (93 runs sampled)
raw mobx x 16,579 ops/sec ±2.49% (89 runs sampled)
Fastest is mobx-keystone by 1.77x
raw mobx is faster by 4.00x
raw es6 is faster by 44.35x

already created, access all simple props (type checking disabled)
mobx-keystone x 314,256 ops/sec ±1.00% (94 runs sampled)
mobx-state-tree x 368,448 ops/sec ±1.29% (93 runs sampled)
raw es6 x 3,300,070 ops/sec ±2.22% (91 runs sampled)
raw mobx x 927,336 ops/sec ±2.16% (88 runs sampled)
Fastest is mobx-state-tree by 1.17x
raw mobx is faster by 2.52x
raw es6 is faster by 8.96x

snapshot creation (type checking disabled)
mobx-keystone x 4,685 ops/sec ±4.67% (84 runs sampled)
mobx-state-tree x 5,090 ops/sec ±1.80% (88 runs sampled)
raw es6 x 184,028 ops/sec ±1.21% (88 runs sampled)
raw mobx x 16,780 ops/sec ±2.55% (87 runs sampled)
Fastest is mobx-state-tree by 1.09x
raw mobx is faster by 3.30x
raw es6 is faster by 36.15x

already created, access all simple props (type checking disabled)
mobx-keystone x 326,125 ops/sec ±1.50% (90 runs sampled)
mobx-state-tree x 298,691 ops/sec ±2.33% (92 runs sampled)
raw es6 x 3,443,478 ops/sec ±1.23% (94 runs sampled)
raw mobx x 940,590 ops/sec ±0.77% (94 runs sampled)
Fastest is mobx-keystone by 1.09x
raw mobx is faster by 2.88x
raw es6 is faster by 10.56x

already created, change all simple props (type checking disabled)
mobx-keystone x 3,711 ops/sec ±4.80% (84 runs sampled)
mobx-state-tree x 1,406 ops/sec ±2.91% (87 runs sampled)
raw es6 x 1,573 ops/sec ±3.45% (88 runs sampled)
raw mobx x 1,604 ops/sec ±2.10% (90 runs sampled)
Fastest is mobx-keystone by 2.64x
raw mobx is faster by 0.43x
raw es6 is faster by 0.42x

already created, change one simple props + getSnapshot (type checking disabled)
mobx-keystone x 137,831 ops/sec ±1.62% (87 runs sampled)
mobx-state-tree x 34,752 ops/sec ±1.66% (85 runs sampled)
raw es6 x 8,884,053 ops/sec ±22.73% (48 runs sampled)
raw mobx:
Fastest is mobx-keystone by 3.97x
raw mobx is faster by 0.00x
raw es6 is faster by 64.46x
```

on top of the other PR cause I thought this one might be a bit more controversial

### CODE REVIEW

**Comment by xaviergonz** [comment]
hey, nice work :)

just a thing, is this test broken in raw mobx?
```
already created, change one simple props + getSnapshot (type checking enabled)
mobx-keystone x 62,599 ops/sec ±1.76% (90 runs sampled)
mobx-state-tree x 34,634 ops/sec ±1.91% (90 runs sampled)
raw es6 x 7,136,654 ops/sec ±62.88% (30 runs sampled)
raw mobx:
Fastest is mobx-keystone by 1.81x
raw mobx is faster by 0.00x
raw es6 is faster by 114.01x
```

**Comment by airhorns** [comment]
Oops, fixed that broken benchmark, here's what I get locally when running it now:

```
already created, change one simple props + getSnapshot (type checking enabled)
mobx-keystone x 99,567 ops/sec ±20.44% (89 runs sampled)
mobx-state-tree x 39,384 ops/sec ±0.91% (89 runs sampled)
raw es6 x 7,005,461 ops/sec ±59.85% (39 runs sampled)
raw mobx x 639,409 ops/sec ±2.23% (87 runs sampled)
Fastest is mobx-keystone by 2.53x
raw mobx is faster by 6.42x
raw es6 is faster by 70.36x

already created, change one simple props + getSnapshot (type checking disabled)
mobx-keystone x 160,108 ops/sec ±1.51% (89 runs sampled)
mobx-state-tree x 36,479 ops/sec ±0.62% (91 runs sampled)
raw es6 x 7,039,694 ops/sec ±57.68% (43 runs sampled)
raw mobx x 598,158 ops/sec ±2.97% (87 runs sampled)
Fastest is mobx-keystone by 4.39x
raw mobx is faster by 3.74x
raw es6 is faster by 43.97x
```

> also, when you say "raw mobx is faster by xxx" is it compared to keystone always or the faster between keystone and mst?

Ah, that's kinda unclear, it's that raw mobx is faster than the fastest full-state-management library (keystone or MST). I can change that to be faster than keystone specifically if you'd prefer

**Comment by xaviergonz** [comment]
> I can change that to be faster than keystone specifically if you'd prefer

That would be great 😊

**Comment by airhorns** [comment]
Ok, here's the result after that change:

```
empty creation (type checking enabled) - mst is usually faster here due to lazy creation
mobx-keystone x 5,177 ops/sec ±4.85% (83 runs sampled)
mobx-state-tree x 5,179 ops/sec ±1.55% (89 runs sampled)
raw es6 x 205,976 ops/sec ±1.74% (95 runs sampled)
raw mobx x 18,615 ops/sec ±0.51% (93 runs sampled)
Fastest is mobx-state-tree by 1.00x
raw mobx is faster than mobx-keystone by 3.60x
raw es6 is faster than mobx-keystone by 39.79x

empty creation + access all simple props (type checking enabled)
mobx-keystone x 5,047 ops/sec ±3.08% (84 runs sampled)
mobx-state-tree x 2,576 ops/sec ±3.43% (88 runs sampled)
raw es6 x 193,001 ops/sec ±1.74% (95 runs sampled)
raw mobx x 17,676 ops/sec ±4.68% (93 runs sampled)
Fastest is mobx-keystone by 1.96x
raw mobx is faster than mobx-keystone by 3.50x
raw es6 is faster than mobx-keystone by 38.24x

already created, access all simple props (type checking enabled)
mobx-keystone x 357,440 ops/sec ±0.51% (95 runs sampled)
mobx-state-tree x 336,369 ops/sec ±0.35% (96 runs sampled)
raw es6 x 3,473,536 ops/sec ±1.86% (93 runs sampled)
raw mobx x 1,024,684 ops/sec ±0.37% (95 runs sampled)
Fastest is mobx-keystone by 1.06x
raw mobx is faster than mobx-keystone by 2.87x
raw es6 is faster than mobx-keystone by 9.72x

snapshot creation (type checking enabled)
mobx-keystone x 4,851 ops/sec ±2.05% (87 runs sampled)
mobx-state-tree x 5,329 ops/sec ±1.25% (93 runs sampled)
raw es6 x 192,508 ops/sec ±1.98% (97 runs sampled)
raw mobx x 17,932 ops/sec ±0.96% (94 runs sampled)
Fastest is mobx-state-tree by 1.10x
raw mobx is faster than mobx-keystone by 3.70x
raw es6 is faster than mobx-keystone by 39.68x

already created, access all simple props (type checking enabled)
mobx-keystone x 359,517 ops/sec ±0.31% (96 runs sampled)
mobx-state-tree x 332,320 ops/sec ±1.53% (96 runs sampled)
raw es6 x 3,481,793 ops/sec ±0.56% (97 runs sampled)
raw mobx x 1,046,507 ops/sec ±0.38% (96 runs sampled)
Fastest is mobx-keystone by 1.08x
raw mobx is faster than mobx-keystone by 2.91x
raw es6 is faster than mobx-keystone by 9.68x

already created, change all simple props (type checking enabled)
mobx-keystone x 2,040 ops/sec ±0.69% (91 runs sampled)
mobx-state-tree x 1,523 ops/sec ±2.12% (90 runs sampled)
raw es6 x 1,755 ops/sec ±1.00% (92 runs sampled)
raw mobx x 1,770 ops/sec ±0.58% (95 runs sampled)
Fastest is mobx-keystone by 1.34x
raw mobx is faster than mobx-keystone by 0.87x
raw es6 is faster than mobx-keystone by 0.86x

already created, change one simple props + getSnapshot (type checking enabled)
mobx-keystone x 63,527 ops/sec ±0.83% (89 runs sampled)
mobx-state-tree x 34,329 ops/sec ±2.24% (89 runs sampled)
raw es6 x 6,232,439 ops/sec ±59.44% (41 runs sampled)
raw mobx x 645,647 ops/sec ±3.50% (82 runs sampled)
Fastest is mobx-keystone by 1.85x
raw mobx is faster than mobx-keystone by 10.16x
raw es6 is faster than mobx-keystone by 98.11x

empty creation (type checking disabled) - mst is usually faster here due to lazy creation
mobx-keystone x 4,600 ops/sec ±5.09% (81 runs sampled)
mobx-state-tree x 4,469 ops/sec ±8.94% (85 runs sampled)
raw es6 x 205,163 ops/sec ±0.32% (97 runs sampled)
raw mobx x 18,039 ops/sec ±1.84% (92 runs sampled)
Fastest is mobx-keystone by 1.03x
raw mobx is faster than mobx-keystone by 3.92x
raw es6 is faster than mobx-keystone by 44.60x

empty creation + access all simple props (type checking disabled)
mobx-keystone x 5,245 ops/sec ±4.36% (79 runs sampled)
mobx-state-tree x 2,397 ops/sec ±3.18% (85 runs sampled)
raw es6 x 188,875 ops/sec ±1.68% (96 runs sampled)
raw mobx x 17,128 ops/sec ±0.79% (92 runs sampled)
Fastest is mobx-keystone by 2.19x
raw mobx is faster than mobx-keystone by 3.27x
raw es6 is faster than mobx-keystone by 36.01x

already created, access all simple props (type checking disabled)
mobx-keystone x 334,405 ops/sec ±0.84% (95 runs sampled)
mobx-state-tree x 375,393 ops/sec ±1.26% (94 runs sampled)
raw es6 x 2,226,953 ops/sec ±10.42% (64 runs sampled)
raw mobx x 629,110 ops/sec ±4.47% (74 runs sampled)
Fastest is mobx-state-tree by 1.12x
raw mobx is faster than mobx-keystone by 1.88x
raw es6 is faster than mobx-keystone by 6.66x

snapshot creation (type checking disabled)
mobx-keystone x 3,822 ops/sec ±5.10% (72 runs sampled)
mobx-state-tree x 4,014 ops/sec ±4.38% (83 runs sampled)
raw es6 x 157,622 ops/sec ±0.13% (95 runs sampled)
raw mobx x 15,334 ops/sec ±0.50% (87 runs sampled)
Fastest is mobx-state-tree by 1.05x
raw mobx is faster than mobx-keystone by 4.01x
raw es6 is faster than mobx-keystone by 41.24x

already created, access all simple props (type checking disabled)
mobx-keystone x 316,679 ops/sec ±1.77% (93 runs sampled)
mobx-state-tree x 362,996 ops/sec ±0.47% (86 runs sampled)
raw es6 x 3,364,192 ops/sec ±0.36% (97 runs sampled)
raw mobx x 1,014,370 ops/sec ±1.76% (89 runs sampled)
Fastest is mobx-state-tree by 1.15x
raw mobx is faster than mobx-keystone by 3.20x
raw es6 is faster than mobx-keystone by 10.62x

already created, change all simple props (type checking disabled)
mobx-keystone x 3,917 ops/sec ±2.30% (89 runs sampled)
mobx-state-tree x 1,668 ops/sec ±0.80% (95 runs sampled)
raw es6 x 1,673 ops/sec ±0.54% (94 runs sampled)
raw mobx x 1,632 ops/sec ±2.14% (92 runs sampled)
Fastest is mobx-keystone by 2.35x
raw mobx is faster than mobx-keystone by 0.42x
raw es6 is faster than mobx-keystone by 0.43x

already created, change one simple props + getSnapshot (type checking disabled)
mobx-keystone x 142,311 ops/sec ±0.69% (96 runs sampled)
mobx-state-tree x 34,185 ops/sec ±0.38% (92 runs sampled)
raw es6 x 9,633,969 ops/sec ±19.89% (31 runs sampled)
raw mobx x 636,578 ops/sec ±2.86% (89 runs sampled)
Fastest is mobx-keystone by 4.16x
raw mobx is faster than mobx-keystone by 4.47x
raw es6 is faster than mobx-keystone by 67.70x
```

**Comment by xaviergonz** [comment]
I think running it with and without type checking is actually a good idea

**Comment by xaviergonz** [comment]
thanks!

**Pull request merged**
